create table if not exists SEGMENTOS(
	ID INTEGER  primary key AUTOINCREMENT  ,
	NOME VARCHAR(200) NOT NULL,
	CNAE VARCHAR(50),
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists IMAGENS(
	ID INTEGER  primary key AUTOINCREMENT,
	PATCH VARCHAR(200) NOT NULL,
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists ENDERECOS(
	ID INTEGER  primary key AUTOINCREMENT,
	LOGADOURO VARCHAR(100),
	NUMERO VARCHAR(10),
	COMPLEMENTO VARCHAR(100),
	CEP VARCHAR(10),
	BAIRRO VARCHAR(50),
	CIDADE VARCHAR(50),
	UF VARCHAR(20),
	PAIS VARCHAR(20),
	HABILITADO BOOL NOT NULL  DEFAULT true	
);

create table if not exists PESSOAS(
	ID INTEGER  primary key AUTOINCREMENT,
	NOME VARCHAR(100)  NOT NULL,
	EMAIL VARCHAR(100),
	TELEFONE VARCHAR(15),
	HABILITADO BOOL NOT NULL  DEFAULT true
);
create table if not exists USUARIOS(
	ID INTEGER  primary key AUTOINCREMENT,
	PESSOA_ID INTEGER  REFERENCES PESSOAS(ID),
	USUARIO VARCHAR(100)  NOT NULL,
	SENHA VARCHAR(100)  NOT NULL,
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists PERFIL(
	ID INTEGER  primary key AUTOINCREMENT,
	USUARIO_ID INTEGER  REFERENCES USUARIOS(ID),
	NOME VARCHAR(100)  NOT NULL,
	HABILITADO BOOL NOT NULL  DEFAULT true 
	
);

create table if not exists PERMISSOES(
	ID INTEGER  primary key AUTOINCREMENT,
	PERFIL_ID INTEGER  NOT NULL REFERENCES PERFIL(ID),
	PERMISSAO VARCHAR(100)  NOT NULL,
	HABILITADO BOOL NOT NULL  DEFAULT true
);


create table if not exists EMPRESAS(
	ID INTEGER  primary key AUTOINCREMENT,
	PAI INTEGER  REFERENCES EMPRESAS(ID),
	RAZAO_SOCIAL VARCHAR(100)  NOT NULL,
	NOME_FANTASIA VARCHAR(100) ,
	CNPJ VARCHAR(50),
	IE VARCHAR(50),
	IM VARCHAR(50),
	TELEFONE VARCHAR(15),
	RESPONSAVEL INTEGER ,
	SEGMENTO INTEGER  REFERENCES SEGMENTOS(ID),
	HABILITADO BOOL NOT NULL  DEFAULT true	
);

create table if not exists CLIENTES(
	ID INTEGER  primary key AUTOINCREMENT,
	PAI INTEGER  REFERENCES CLIENTES(ID),
	RAZAO_SOCIAL VARCHAR(100)  NOT NULL,
	NOME_FANTASIA VARCHAR(100) ,
	CNPJ VARCHAR(50),
	IE VARCHAR(50),
	IM VARCHAR(50),
	TELEFONE VARCHAR(15),
	RESPONSAVEL INTEGER ,
	SEGMENTO INTEGER  REFERENCES SEGMENTOS(ID),
	HABILITADO BOOL NOT NULL  DEFAULT true	
);

create table if not exists PESSOAS_DE_EMPRESAS(
	ID INTEGER  primary key AUTOINCREMENT,
	PESSOA_ID INTEGER  NOT NULL REFERENCES PESSOAS(ID),
	EMPRESA_ID INTEGER  NOT NULL REFERENCES EMPRESAS(ID),
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists PESSOAS_DE_CLIENTES(
	ID INTEGER  primary key AUTOINCREMENT ,
	PESSOA_ID INTEGER  NOT NULL REFERENCES PESSOAS(ID),
	CLIENTE_ID INTEGER  NOT NULL REFERENCES CLIENTES(ID),
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists ENDERECOS_DE_CLIENTES(
	ID INTEGER  primary key AUTOINCREMENT,
	CLIENTE_ID INTEGER  NOT NULL REFERENCES CLIENTES(ID),
	ENDERECO_ID INTEGER  NOT NULL REFERENCES ENDERECOS(ID),
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists ENDERECOS_DE_EMPRESAS(
	ID INTEGER  primary key AUTOINCREMENT,
	EMPRESA_ID INTEGER  NOT NULL REFERENCES EMPRESAS(ID),
	ENDERECO_ID INTEGER  NOT NULL REFERENCES ENDERECOS(ID),
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists ENDERECOS_DE_PESSOAS(
	ID INTEGER  primary key AUTOINCREMENT,
	PESSOA_ID INTEGER  NOT NULL REFERENCES PESSOAS(ID),
	ENDERECO_ID INTEGER  NOT NULL REFERENCES ENDERECOS(ID),
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists FOTOS_DE_PERFIL(
	ID INTEGER  primary key AUTOINCREMENT,
	PESSOA_ID INTEGER  NOT NULL REFERENCES PESSOAS(ID),
	IMAGEM_ID INTEGER  NOT NULL REFERENCES IMAGENS(ID),
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists LOGO_EMPRESAS(
	ID INTEGER  primary key AUTOINCREMENT,
	EMPRESA_ID INTEGER  NOT NULL REFERENCES EMPRESAS(ID),
	IMAGEM_ID INTEGER  NOT NULL REFERENCES IMAGENS(ID),
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists LOGO_CLIENTES(
	ID INTEGER  primary key AUTOINCREMENT,
	CLIENTE_ID INTEGER  NOT NULL REFERENCES CLIENTES(ID),
	IMAGEM_ID INTEGER  NOT NULL REFERENCES IMAGENS(ID),
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists CLIENTES_DE_EMPRESAS(
	ID INTEGER  primary key AUTOINCREMENT,
	CLIENTE_ID INTEGER NOT NULL REFERENCES CLIENTES(ID),
	EMPRESA_ID INTEGER NOT NULL REFERENCES EMPRESAS(ID),
	HABILITADO BOOL NOT NULL  DEFAULT true
	
	
);

create table if not exists PERFIS_DE_USUARIOS(
	ID INTEGER  primary key AUTOINCREMENT,
	USUARIO_ID INTEGER NOT NULL REFERENCES USUARIOS(ID),
	PERFIL_ID INTEGER NOT NULL REFERENCES PERFIL(ID),
	HABILITADO BOOL NOT NULL  DEFAULT true
);
