
CREATE DATABASE cogni
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
	



create table if not exists PESSOAS_DE_EMPRESAS_CLIENTES(
	ID_PESSOAS_DE_EMPRESAS_CLIENTES SERIAL primary key NOT NULL ,
	PESSOA INT NOT NULL REFERENCES PESSOAS(ID_PESSOA),
	CLIENTE INT DEFAULT 0 REFERENCES CLIENTES(ID_CLIENTE),
	EMPRESA INT  DEFAULT 0 REFERENCES EMPRESAS(ID_EMPRESA)
);


	 
	 
--ATIVOS

create table if not exists VARIAVEIS_DE_CONTROLE(
	ID_VARIAVEIL_DE_CONTROLE SERIAL primary key NOT NULL ,
	NOME VARCHAR(100)  NOT NULL,
	VALOR_REFERENCIA FLOAT ,
	UN_MEDIDA VARCHAR(50),
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists PRODUTOS(
	ID_PRODUTO SERIAL primary key NOT NULL ,
	NOME VARCHAR(100)  NOT NULL,
	CODIGO VARCHAR(100)  NOT NULL,
	EMPRESA INT NOT NULL REFERENCES CLIENTES(ID_CLIENTE),
	HABILITADO BOOL NOT NULL  DEFAULT true
);


create table if not exists PRODUTOS_ASSOCIADOS_A_VARIAVEIS_DE_CONTROLE(
	ID_ASSOCIACAO SERIAL primary key NOT NULL ,
	VARIAVEL_DE_CONTROLE INT NOT NULL REFERENCES VARIAVEIS_DE_CONTROLE(ID_VARIAVEIL_DE_CONTROLE),
	PRODUTO INT NOT NULL REFERENCES PRODUTOS(ID_PRODUTO),
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists TIPOS_HIERARQUIA(
	ID_TIPO SERIAL primary key NOT NULL ,
	NOME VARCHAR(100)  NOT NULL,
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists HIERARQUIAS(
	ID_HIERARQUIA SERIAL primary key NOT NULL ,
	NOME VARCHAR(100)  NOT NULL,
	TAG VARCHAR(100),
	PAI INT REFERENCES HIERARQUIAS(ID_HIERARQUIA),
	TIPO INT REFERENCES TIPOS_HIERARQUIA(ID_TIPO),
	RESPONSAVEL INT REFERENCES PESSOAS(ID_PESSOA),
	EMPRESA INT NOT NULL REFERENCES CLIENTES(ID_CLIENTE),
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists PRODUTOS_DE_PROCESSOS(
	ID_PRODUTOS_DE_PROCESSOS SERIAL primary key NOT NULL ,
	PROCESSO INT NOT NULL REFERENCES HIERARQUIAS(ID_HIERARQUIA),
	PRODUTO INT NOT NULL REFERENCES PRODUTOS(ID_PRODUTO),
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists ATIVOS(
	ID_ATIVO SERIAL primary key NOT NULL ,
	NOME VARCHAR(100)  NOT NULL,
	TAG VARCHAR(100),
	PAI INT REFERENCES ATIVOS(ID_ATIVO),
	HIERARQUIA INT REFERENCES HIERARQUIAS(ID_HIERARQUIA),
	EMPRESA INT NOT NULL REFERENCES CLIENTES(ID_CLIENTE),
	RESPONSAVEL INT REFERENCES PESSOAS(ID_PESSOA),	
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists FOTOS_DE_ATIVOS(
	ID_FOTOS_DE_ATIVOS SERIAL primary key NOT NULL ,
	ATIVO INT NOT NULL REFERENCES ATIVOS(ID_ATIVO),
	IMAGEM INT NOT NULL REFERENCES IMAGENS(ID_IMAGEM),
	HABILITADO BOOL NOT NULL  DEFAULT true
);


CREATE DATABASE cogni
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
	
create table if not exists SEGMENTOS(
	ID_SEGMENTO SERIAL primary key NOT NULL,
	NOME VARCHAR(200) NOT NULL,
	CNAE VARCHAR(50),
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists IMAGENS(
	ID_IMAGEM SERIAL primary key NOT NULL ,
	PATCH VARCHAR(200) NOT NULL,
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists ENDERECOS(
	ID_ENDERECO SERIAL primary key NOT NULL ,
	LOGADOURO VARCHAR(100),
	NUMERO VARCHAR(10),
	COMPLEMENTO VARCHAR(100),
	CEP VARCHAR(10),
	BAIRRO VARCHAR(50),
	CIDADE VARCHAR(50),
	UF VARCHAR(20),
	PAIS VARCHAR(20),
	HABILITADO BOOL NOT NULL  DEFAULT true	
);

create table if not exists PERFIL(
	ID_PERFIL SERIAL primary key NOT NULL ,
	NOME VARCHAR(100)  NOT NULL,
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists PESSOAS(
	ID_PESSOA SERIAL primary key NOT NULL,
	NOME VARCHAR(100)  NOT NULL,
	ENDERECO INT  REFERENCES ENDERECOS(ID_ENDERECO),
	EMAIL VARCHAR(100),
	TELEFONE VARCHAR(15),
	FOTO_PERFIL INT  REFERENCES IMAGENS(ID_IMAGEM),
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists USUARIOS(
	ID_USUARIO SERIAL primary key NOT NULL ,
	PESSOA INT REFERENCES PESSOAS(ID_PESSOA),
	USUARIO VARCHAR(100)  NOT NULL,
	SENHA VARCHAR(100)  NOT NULL,
	PERFIL INT NOT NULL REFERENCES PERFIL(ID_PERFIL),
	HABILITADO BOOL NOT NULL  DEFAULT true
);


create table if not exists PERMISSOES(
	ID_PERMISSAO SERIAL primary key NOT NULL ,
	PERFIL INT NOT NULL REFERENCES PERFIL(ID_PERFIL),
	PERMISSAO VARCHAR(100)  NOT NULL,
	HABILITADO BOOL NOT NULL  DEFAULT true
);


create table if not exists EMPRESAS(
	ID_EMPRESA SERIAL primary key NOT NULL ,
	PAI INT REFERENCES EMPRESAS(ID_EMPRESA),
	LOGOMARCA INT REFERENCES IMAGENS(ID_IMAGEM),
	RAZAO_SOCIAL VARCHAR(100)  NOT NULL,
	NOME_FANTASIA VARCHAR(100) ,
	CNPJ VARCHAR(50),
	IE VARCHAR(50),
	IM VARCHAR(50),
	TELEFONE VARCHAR(15),
	RESPONSAVEL INT,
	ENDERECO INT REFERENCES ENDERECOS(ID_ENDERECO),
	SEGMENTO INT REFERENCES SEGMENTOS(ID_SEGMENTO),
	HABILITADO BOOL NOT NULL  DEFAULT true	
);

create table if not exists CLIENTES(
	ID_CLIENTE SERIAL primary key NOT NULL ,
	PAI INT REFERENCES CLIENTES(ID_CLIENTE),
	LOGOMARCA INT REFERENCES IMAGENS(ID_IMAGEM),
	RAZAO_SOCIAL VARCHAR(100)  NOT NULL,
	NOME_FANTASIA VARCHAR(100) ,
	CNPJ VARCHAR(50),
	IE VARCHAR(50),
	IM VARCHAR(50),
	TELEFONE VARCHAR(15),
	RESPONSAVEL INT,
	ENDERECO INT REFERENCES ENDERECOS(ID_ENDERECO),
	SEGMENTO INT REFERENCES SEGMENTOS(ID_SEGMENTO),
	HABILITADO BOOL NOT NULL  DEFAULT true	
);

create table if not exists PESSOAS_DE_EMPRESAS_CLIENTES(
	ID_PESSOAS_DE_EMPRESAS_CLIENTES SERIAL primary key NOT NULL ,
	PESSOA INT NOT NULL REFERENCES PESSOAS(ID_PESSOA),
	CLIENTE INT DEFAULT 0 REFERENCES CLIENTES(ID_CLIENTE),
	EMPRESA INT  DEFAULT 0 REFERENCES EMPRESAS(ID_EMPRESA)
);

INSERT INTO public.imagens (patch,habilitado) VALUES
	 ('C:\LogoEmpresa.jpg',true),
	 ('C:\AvatarPessoa.jpg',true),
	 ('C:\LogoDell.jpg',true);
	 
INSERT INTO public.segmentos (nome,cnae,habilitado) VALUES 
('SEEGMENTO PADRÃO','0',true)
;
INSERT INTO public.enderecos (logadouro,numero,complemento,cep,bairro,cidade,uf,pais,habilitado) VALUES 
('R. Armogaste José da Silveira','612','Predio IST','74560550','Centro Oeste','Goiânia','GO','Brasil',true)
;
INSERT INTO public.enderecos (logadouro,numero,complemento,cep,bairro,cidade,uf,pais,habilitado) VALUES 
('AV INDUSTRIAL BELGRAF','400','***','92.990-000','Industrial','Eldorado do Sul','RS','Brasil',true)
;

INSERT INTO public.pessoas (nome,endereco,email,telefone,foto_perfil,habilitado) VALUES 
('PESSOA',1,'exemplo@exemplo.com','62986430239',2,true)
;

INSERT INTO public.empresas (pai,logomarca,razao_social,nome_fantasia,cnpj,ie,im,telefone,responsavel,endereco,segmento,habilitado) VALUES 
(NULL,1,'SERVICO NACIONAL DE APRENDIZAGEM INDUSTIAL SENAI','INSTITUTO SENAI DE TECNOLOGIA EM AUTOMAÇÃO','03783850001840','ISENTO','ISENTO','32264509',1,1,1,true)
;
INSERT INTO public.empresas (pai,logomarca,razao_social,nome_fantasia,cnpj,ie,im,telefone,responsavel,endereco,segmento,habilitado) VALUES 
(1,1,'FILIAL DO SENAI','INSTITUTO SENAI DE TECNOLOGIA EM AUTOMAÇÃO (FILIAL)','03783850001840','ISENTO','ISENTO','32264509',1,1,1,true)
;

INSERT INTO public.clientes (pai,logomarca,razao_social,nome_fantasia,cnpj,ie,im,telefone,responsavel,endereco,segmento,habilitado) VALUES 
(NULL,3,'DELL COMPUTADORES DO BRASIL LTDA','DELL BRASIL (FILIAL)','72381189000110','0000','0000','(51) 3274-5500',1,2,1,true)
;
INSERT INTO public.clientes (pai,logomarca,razao_social,nome_fantasia,cnpj,ie,im,telefone,responsavel,endereco,segmento,habilitado) VALUES 
(1,3,'FILIAL DA DELL BRASIL LTDA','DELL BRASIL','72381189000110','0000','0000','(62) 3274-5500',1,2,1,true)
;
INSERT INTO public.perfil (nome,habilitado) VALUES
	 ('Administrador Cogni',true),
	 ('Administrador Cliente',true);

INSERT INTO public.permissoes (perfil,permissao,habilitado) VALUES
	 (1,'Visualiza Todos Clientes',true),
	 (2,'Visualiza Todos Clientes',false);

INSERT INTO public.usuarios (pessoa,usuario,senha,perfil,habilitado) VALUES
	 (1,'admin','admin',1,true);
	 
	 
--ATIVOS

create table if not exists VARIAVEIS_DE_CONTROLE(
	ID_VARIAVEIL_DE_CONTROLE SERIAL primary key NOT NULL ,
	NOME VARCHAR(100)  NOT NULL,
	VALOR_REFERENCIA FLOAT ,
	UN_MEDIDA VARCHAR(50),
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists PRODUTOS(
	ID_PRODUTO SERIAL primary key NOT NULL ,
	NOME VARCHAR(100)  NOT NULL,
	CODIGO VARCHAR(100)  NOT NULL,
	EMPRESA INT NOT NULL REFERENCES CLIENTES(ID_CLIENTE),
	HABILITADO BOOL NOT NULL  DEFAULT true
);


create table if not exists PRODUTOS_ASSOCIADOS_A_VARIAVEIS_DE_CONTROLE(
	ID_ASSOCIACAO SERIAL primary key NOT NULL ,
	VARIAVEL_DE_CONTROLE INT NOT NULL REFERENCES VARIAVEIS_DE_CONTROLE(ID_VARIAVEIL_DE_CONTROLE),
	PRODUTO INT NOT NULL REFERENCES PRODUTOS(ID_PRODUTO),
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists TIPOS_HIERARQUIA(
	ID_TIPO SERIAL primary key NOT NULL ,
	NOME VARCHAR(100)  NOT NULL,
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists HIERARQUIAS(
	ID_HIERARQUIA SERIAL primary key NOT NULL ,
	NOME VARCHAR(100)  NOT NULL,
	TAG VARCHAR(100),
	PAI INT REFERENCES HIERARQUIAS(ID_HIERARQUIA),
	TIPO INT REFERENCES TIPOS_HIERARQUIA(ID_TIPO),
	RESPONSAVEL INT REFERENCES PESSOAS(ID_PESSOA),
	EMPRESA INT NOT NULL REFERENCES CLIENTES(ID_CLIENTE),
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists PRODUTOS_DE_PROCESSOS(
	ID_PRODUTOS_DE_PROCESSOS SERIAL primary key NOT NULL ,
	PROCESSO INT NOT NULL REFERENCES HIERARQUIAS(ID_HIERARQUIA),
	PRODUTO INT NOT NULL REFERENCES PRODUTOS(ID_PRODUTO),
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists ATIVOS(
	ID_ATIVO SERIAL primary key NOT NULL ,
	NOME VARCHAR(100)  NOT NULL,
	TAG VARCHAR(100),
	PAI INT REFERENCES ATIVOS(ID_ATIVO),
	HIERARQUIA INT REFERENCES HIERARQUIAS(ID_HIERARQUIA),
	EMPRESA INT NOT NULL REFERENCES CLIENTES(ID_CLIENTE),
	RESPONSAVEL INT REFERENCES PESSOAS(ID_PESSOA),	
	HABILITADO BOOL NOT NULL  DEFAULT true
);

create table if not exists FOTOS_DE_ATIVOS(
	ID_FOTOS_DE_ATIVOS SERIAL primary key NOT NULL ,
	ATIVO INT NOT NULL REFERENCES ATIVOS(ID_ATIVO),
	IMAGEM INT NOT NULL REFERENCES IMAGENS(ID_IMAGEM),
	HABILITADO BOOL NOT NULL  DEFAULT true
);

